doctrine:
    # dbal:
    #     url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    dbal:
        default_connection: dbname
        connections:
            dbname:
                # configure these for your database server
                # url: '%env(DATABASE_URL)%'
                url: "%env(DEFAULT_DB_ENGINE)%://%env(DEFAULT_DB_USER)%:\
                    %env(DEFAULT_DB_PASSWORD)%@%env(DEFAULT_DB_HOST)%:\
                    %env(DEFAULT_DB_PORT)%/%env(DEFAULT_DB_NAME)%?\
                    serverVersion=%env(DEFAULT_DB_SERVER_VERSION)%"
                driver: 'pdo_mysql'
                server_version: '%env(DEFAULT_DB_SERVER_VERSION)%'
                charset: utf8mb4
                mapping_types:
                    enum: string
                wrapper_class: App\Doctrine\DynamicConnection

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
